name: aisparkhub
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.0
  - pip:
    - PyQt6==6.5.0
    - PyQt6-Qt6==6.5.0
    - PyQt6_sip==13.10.0
    - PyQt6-WebEngine==6.5.0
    - PyQt6-WebEngine-Qt6==6.5.0
    - qtawesome==1.4.0
    - libsql-experimental==0.1.4
    - pathlib==1.0.1
    - pywin32==306; platform_system == "Windows" 